# Generated by Django 4.1.5 on 2023-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accounts_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
